[workspace]
members = [
  "crates/full-node",
  "crates/sequencer",
  "crates/utils",
  "crates/prover",
  "crates/proof-coordinator",
  "crates/signature",
  "crates/utils",
  "crates/tests",
  "tooling/load_generator",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# ethrex
ethrex = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
zkvm_interface = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-blockchain = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-l2 = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-l2-common = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-l2-rpc = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-metrics = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-rpc = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-storage-rollup = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-vm = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967", default-features = false }
ethrex-common = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967" }
ethrex-p2p = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967" }
ethrex-rlp = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967" }
ethrex-storage = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967" }
ethrex-prover = { git = "https://github.com/1sixtech/ethrex", rev = "9a771ea8f3b895153a5f122caab87a1e7e6f7967" }

# mojave
mojave-block-builder = { path = "crates/block-builder" }
mojave-chain-utils = { path = "crates/utils" }
mojave-client = { path = "crates/client" }
mojave-full-node = { path = "crates/full-node" }
mojave-prover = { path = "crates/prover" }
mojave-sequencer = { path = "crates/sequencer" }
mojave-signature = { path = "crates/signature" }
mojave-tests = { path = "crates/tests" }

anyhow = { version = "1.0" }
axum = "0.8.1"
clap = { version = "4.5", default-features = false }
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "serde"] }
futures = "0.3"
hex = "0.4.3"
k256 = { version = "0.13.3", features = ["ecdh"] }
lazy_static = "1.5.0"
rand = { version = "0.8.5", default-features = false }
reqwest = { version = "0.12.7", features = ["json"] }
secp256k1 = { version = "0.29.1", default-features = false, features = [
  "serde",
] }
serde = { version = "1.0", default-features = false }
serde_json = "1.0"
thiserror = "2"
tokio = { version = "1", default-features = false }
tokio-stream = { version = "0.1.17" }
tokio-util = { version = "0.7", default-features = false }
tower-http = { version = "0.6.2", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
trait-variant = "0.1"

[patch.crates-io]
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.29.1-sp1-5.0.0" }
