[workspace]
members = [
	"crates/abci",
	"crates/node",
	"crates/rpc",
	"crates/subscriber",
	"crates/types",
]
resolver = "2"

[workspace.dependencies]
futures = "0.3"
serde = { version = "1", default-features = false }
tokio = { version = "1", default-features = false }
tokio-stream = "0.1"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
trait-variant = "0.1"

drip-chain-abci = { path = "crates/abci" }
drip-chain-node = { path = "crates/node" }
drip-chain-rpc = { path = "crates/rpc" }
drip-chain-types = { path = "crates/types" }
