[workspace]
members = ["cmd/mojave", "crates/json-rpc", "crates/full-node"]
resolver = "2"

[workspace.dependencies]
mojave-chain-json-rpc = { path = "crates/json-rpc" }
mojave-chain-full-node = { path = "crates/full-node" }
tokio = { version = "1", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
trait-variant = "0.1"
clap = { version = "4.5", features = ["derive"] }

# error handling
thiserror = "2"
anyhow = { version = "1.0" }
