[workspace]
members = [
    "crates/abci",
    "crates/evm",
    "crates/node",
    "crates/rpc",
]
resolver = "2"

[workspace.dependencies]
alloy = { version = "0.12", default-features = false }
futures = "0.3"
serde = { version = "1", default-features = false }
tokio = { version = "1", default-features = false }
tokio-stream = "0.1"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
trait-variant = "0.1"

mandu-abci = { path = "crates/abci" }
mandu-evm = { path = "crates/evm" }
mandu-node = { path = "crates/node" }
mandu-rpc = { path = "crates/rpc" }