[workspace]
members = [
    "crates/evm",
    "crates/rpc",
]
resolver = "2"

[workspace.dependencies]
alloy = { version = "0.12", default-features = false }
futures = "0.3"
serde = { version = "1", default-features = false }
tokio = { version = "1", default-features = false }
trait-variant = "0.1.2"