[package]
name = "mojave"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mojave"
path = "./mojave.rs"

[lib]
name = "mojave"
path = "./lib.rs"

[dependencies]
tokio = { workspace = true, features = ["full"] }

# logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# misc
clap = { workspace = true, features = ["derive", "env", "string"] }
anyhow = { version = "1.0" }
