[package]
name = "mandu-node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mandu-node"
path = "src/bin/main.rs"

[dependencies]
# alloy = { workspace = true, features = ["consensus", "eips", "k256", "network", "rlp"] }
bytes = "1.9"
futures = { workspace = true }
mandu-abci = { workspace = true }
mandu-rpc = { workspace = true }
mandu-types = { workspace = true }
revm = { git = "https://github.com/bluealloy/revm", tag = "v66" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = "0.1"