[package]
name = "mandu-node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mandu-node"
path = "src/bin/main.rs"

[dependencies]
anvil = { git = "https://github.com/foundry-rs/foundry" }
futures = { workspace = true }
mandu-abci = { workspace = true }
mandu-rpc = { workspace = true }
mandu-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1"
tokio = { workspace = true, features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"