[package]
name = "mojave-prover"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mojave-prover"
path = "src/bin/main.rs"
required-features = ["server"]

[dependencies]
# ethrex
ethrex-l2-common = { workspace = true }
ethrex-prover = { workspace = true }
ethrex-rpc = { workspace = true }
zkvm_interface = { workspace = true }


# mojave
mojave-chain-utils = { workspace = true }

axum = { workspace = true }
bincode ={ workspace = true}
clap = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tiny-keccak = { workspace = true, features = ["keccak"] }
tokio = { workspace = true, features = ["sync", "net"] }
tower-http = { workspace = true, features = ["cors"] }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = [
  "io-util",
  "macros",
  "rt-multi-thread",
  "time",
] }