[package]
name = "mojave-prover"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "net"] }
serde_json = { workspace = true }
tracing = { workspace = true }

ethrex-l2-common = { workspace = true }
ethrex-prover = { workspace = true }

mojave-common = { workspace = true }
[dev-dependencies]

[features]
