[package]
name = "mojave-prover-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
mojave-utils = { workspace = true }

clap = { workspace = true }
ethrex-l2-common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "net"] }
zkvm_interface = { workspace = true }


# server only dep
ethrex-prover = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = [
	"io-util",
	"macros",
	"rt-multi-thread",
	"time",
] }

[features]
default = []
client = []
server = ["ethrex-prover", "tracing"]
