[package]
name = "mojave-prover"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync", "net"] , optional = true}
tracing = { workspace = true , optional = true}

# server only dep
ethrex-l2-common = { workspace = true , optional = true}
ethrex-prover = { workspace = true , optional = true}
zkvm_interface = { workspace = true , optional = true}

[dev-dependencies]

[features]
default = []
client = []
server = ["ethrex-l2-common", "ethrex-prover", "zkvm_interface"]