[package]
name = "mojave-node"
version = "0.1.0"
edition = "2024"

[dependencies]
mojave-node-lib = { workspace = true }
mojave-utils = { workspace = true }

clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
