[package]
name = "mandu-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true, features = ["json-rpc", "rpc-types", "serde"] }
jsonrpsee = { version = "0.24", features = ["server"] }
hyper = "1.6.0"
serde = { workspace = true, features = ["derive"] }
tower = "0.4"
tower-http = { version = "0.6", features = ["cors"] }
trait-variant = { workspace = true }