[package]
name = "mandu-types"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.12", features = ["json-rpc", "rpc-types", "serde"] }
serde = { workspace = true, features = ["derive"] }