[package]
name = "mandu-types"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.12", features = ["consensus", "eips", "json-rpc", "k256", "network", "rlp", "rpc-types", "serde"] }
serde = { workspace = true, features = ["derive"] }