[package]
name = "mojave-batch-submitter"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }

[dependencies]
bitcoincore-rpc = "0.19.0"
tokio = { version = "1.36.0", features = ["full"] }
anyhow = "1.0.80"
thiserror = "1.0.57"
bitcoin = { workspace = true }
secp256k1 = { workspace = true, features = ["global-context"] }
rand = "0.8.5"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
