[package]
name = "mojave-prover"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mojave-prover"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
ethrex-l2-common = { workspace = true }
ethrex-prover = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "net"] }
zkvm_interface = { workspace = true }

mojave-utils = { workspace = true }

tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = [
	"io-util",
	"macros",
	"rt-multi-thread",
	"time",
] }
