---
name: Task - Docker Build
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Install just
        uses: extractions/setup-just@v1
      - name: Build Docker image
        run: just docker-build
