---
name: Task - Build & Release Binaries
on:
  workflow_dispatch:
    inputs:
      release_tag_name:
        description: "Release tag name"
        type: string
        required: true
  workflow_call:
    inputs:
      release_tag_name:
        description: "Release tag name"
        type: string
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            system: macos-amd64
          - os: ubuntu-latest
            system: linux-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release
      - run: mv target/release/mojave-node target/release/${{ matrix.system }}-mojave-node
      - run: mv target/release/mojave-prover target/release/${{ matrix.system }}-mojave-prover
      - run: mv target/release/mojave-sequencer target/release/${{ matrix.system }}-mojave-sequencer
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/*mojave-{node,prover,sequencer}
          tag: ${{ inputs.release_tag_name }}
          overwrite: true
          file_glob: true
