---
name: Task - Linters Cargo
on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ci

      - name: Rustfmt
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --no-deps -- -D warnings
