---
name: Task - Linters
on:
  workflow_dispatch:
  workflow_call:

jobs:
  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Taplo CLI
        run: cargo install taplo-cli
      - name: Run taplo
        run: |
          taplo check --default-schema-catalogs
          taplo fmt --check --diff
