---
name: Task - Linters
on:
  workflow_dispatch:
  workflow_call:

jobs:
  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uncenter/setup-taplo@v1
        with:
          version: "0.10.0"
      - name: Run toml check
        run: |
          taplo check --default-schema-catalogs
          taplo fmt --check --diff
