---
name: Task - Linters
on:
  workflow_dispatch:
  workflow_call:

jobs:
  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install prebuilt binary (more fast)
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - run: |
          taplo check --default-schema-catalogs
          taplo fmt --check --diff