---
name: Task - Build (Production)
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ci

      - run: cargo build --workspace --release

      - name: Upload prod bins
        uses: actions/upload-artifact@v4
        with:
          name: prod-bins
          path: |
            target/release/mojave-node
            target/release/mojave-sequencer
            target/release/mojave-prover