---
name: Workflow - Release
on:
  workflow_dispatch:
  release:
    types: [created]

concurrency:
  group: release-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-release:
    name: Build & Release Binaries
    uses: ./.github/workflows/task.release-binaries.yml

  docker:
    name: Build & Push Docker Image
    uses: ./.github/workflows/task.docker.yml
    needs: [build-release]
