---
name: Workflow - Release
on:
  workflow_dispatch:
  release:
    types: [created]

concurrency:
  group: release-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-prod:
    name: Build Production
    uses: ./.github/workflows/task.build-prod.yml

  # release binaries to GitHub Releases

  docker:
    name: Build & Push Docker Image
    uses: ./.github/workflows/task.docker.yml
    needs: [build-prod]
